<?php

class PHPTAL_PhpCodeGenerator
{
    public function __construct($sourcePath)
    {
        $this->_functionName = 'tpl_'.PHPTAL_VERSION.md5($sourcePath);
        $this->_sourceFile = $sourcePath;
        $this->_generator = new PHPTAL_CodeGenerator();
    }

    public function setOutputMode($mode)
    { 
        $this->_generator->setOutputMode($mode); 
    }
    
    public function setEncoding($enc)
    { 
        $this->_generator->setEncoding($enc); 
    }

    public function generate(PHPTAL_NodeTree $tree)
    {
        $tree->setGenerator($this->_generator);

        $header = sprintf('Generated by PHPTAL from %s', $this->_sourceFile);
        $this->_generator->doFunction($this->_functionName, '$tpl, $ctx');
        $this->_generator->doComment($header);
        $this->_generator->setFunctionPrefix($this->_functionName . "_");
        $this->_generator->pushCode('ob_start()');
        $tree->generate();
        $this->_generator->pushCode('$_result_ = ob_get_contents()');
        $this->_generator->pushCode('ob_end_clean()');
        $this->_generator->pushCode('return $_result_');
        $this->_generator->doEnd();
    }

    public function getResult()
    {
        return $this->_generator->getResult();
    }

    private $_functionName;
    private $_sourceFile;
    private $_generator;
}

?>
