<?php

require_once 'PHPTAL/PhpGenerator/CodeGenerator.php';

class PHPTAL_PhpCodeGenerator
{
    public function __construct($sourceFile)
    {
        $this->_templateFunctionName = 'tpl_'.PHPTAL_VERSION.md5($sourceFile);
        $this->_sourceFile = $sourceFile;
        $this->_generator = new PHPTAL_CodeGenerator();
    }

    public function setEncoding($enc)
    {
        $this->_generator->setEncoding($enc);
    }
    
    public function setOutputMode($mode)
    {
        $this->_generator->setOutputMode($mode);
    }

    public function generate(PHPTAL_NodeTree $tree)
    {
        $generator = $this->_generator;
        $tree->setGenerator($generator);
        
        $header = sprintf('Generated by PHPTAL from %s', $this->_sourceFile);
        $generator->doFunction($this->_templateFunctionName, '$tpl, $ctx');
        $generator->doComment($header);
        $generator->setFunctionPrefix($this->_templateFunctionName.'_');
        $generator->pushCode('ob_start()');
        $tree->generate();
        $generator->pushCode('$_result_ = ob_get_contents()');
        $generator->pushCode('ob_end_clean()');
        $generator->pushCode('return $_result_');
        $generator->doEnd();
    }

    public function getResult()
    {
        return $this->_generator->getResult();
    }

    private $_generator;
    private $_templateFunctionName;
    private $_sourceFile;
}

?>
